# Generated by Django 4.0.1 on 2022-04-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('trackingnum', models.AutoField(primary_key=True, serialize=False)),
                ('destx', models.IntegerField(blank=True, null=True)),
                ('desty', models.IntegerField(blank=True, null=True)),
                ('warehouseid', models.IntegerField()),
                ('status', models.CharField(choices=[('delivered', 'The packaged has been delivered'), ('delivering', 'The package is under delivering'), ('wait_for_loading', 'The package is waiting for loading'), ('wait_for_pickup', 'The package is waiting for pickup')], default='wait_for_pickup', max_length=20)),
            ],
            options={
                'db_table': 'packages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Searchhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'searchhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truckid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('idle', 'The truck is idle'), ('traveling', 'The truck is traveling for picking up packages'), ('arrive_warehouse', 'The truck arrived at warehouse'), ('loading', 'The truck is loading packages'), ('delivering', 'The truck is delivering ')], default='idle', max_length=20)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'trucks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouseid', models.IntegerField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'warehouses',
                'managed': False,
            },
        ),
    ]
